const app ={
    LOGIN_REQUEST: 'REQUESTING_LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESSFUL',
    LOGIN_FAILED: 'LOGIN_FAILURE',

    LOGOUT_REQUEST: 'REQUESTING_LOGOUT',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESSFULL',
    LOGOUT_FAILED: 'LOGOUT_FAILURE'
}

const user = {
    REGISTER_REQUEST: 'REQUESTING_REGISTRATION',
    REGISTER_SUCCESS: 'REGISTERED',
    REGISTER_FAILURE: 'REGISTING_FAILURE',
    
}
const menu={
    INDEX_REQUEST: 'INDEX_REQUEST',
    INDEX_FAILURE: 'INDEX_FAILURE',
    INDEX_SUCCESS: 'INDEX_SUCCESS',
 
    CREATE_REQUEST: 'ITEM_CREATE_REQUEST',
    CREATE_FAILURE: 'ITEM_CREATE_FAILURE',
    CREATE_SUCCESS: 'ITEM_CREATE_SUCCESS',
 
    UPDATE_REQUEST: 'ITEM_UPDATE_REQUEST',
    UPDATE_FAILURE: 'ITEM_UPDATE_FAILURE',
    UPDATE_SUCCESS: 'ITEM_UPDATE_SUCCESS',
 
    DELETE_REQUEST: 'ITEM_DELETE_REQUEST',
    DELETE_FAILURE: 'ITEM_DELETE_FAILURE',
    DELTE_SUCCESS: 'ITEM_DELETE_SUCCESS'
} 

export const actionCreator = {
       app,
       menu,
       user
}