const app ={
    SESSION_REQUEST: 'REQUESTING_SESSION',
    SESSION_FAILURE: 'REQUEST_FAILED',
    SESSION_SUCCESS: 'ACTIVE_SESSION',

    SESSION_END_REQUEST: 'REQUESTING_SESSION_TERMINATION',
    SESSION_END_SUCCESS: 'SESSION_TERMINATED',
    SESSION_END_FAILURE: 'FAILURE_SESSION_TERMINATION'
}

const user = {
    REGISTER_REQUEST: 'REQUESTING_REGISTRATION',
    REGISTER_SUCCESS: 'REGISTERED',
    REGISTER_FAILURE: 'REGISTING_FAILURE'
}
const menu={
    INDEX_REQUEST: 'INDEX_REQUEST',
    INDEX_SUCCESS: 'INDEX_SUCCESS',
    INDEX_FAILURE: 'INDEX_FAILURE',
 
    CREATE_REQUEST: 'ITEM_CREATE_REQUEST',
    CREATE_SUCCESS: 'ITEM_CREATE_SUCCESS',
    CREATE_FAILURE: 'ITEM_CREATE_FAILURE',
 
    UPDATE_REQUEST: 'ITEM_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'ITEM_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'ITEM_UPDATE_FAILURE',
 
    DELETE_REQUEST: 'ITEM_DELETE_REQUEST',
    DELTE_SUCCESS: 'ITEM_DELETE_SUCCESS',
    DELETE_FAILURE: 'ITEM_DELETE_FAILURE'
} 

export const actionCreator = {
       app,
       menu,
       user
}